-------------------
DROP DATABASE  IF EXISTS ServListDB;
---------------------------
CREATE DATABASE ServListDB
       OWNER  postgres
       ENCODING  'UTF8'
       TABLESPACE  pg_default
       CONNECTION LIMIT  -1;
----------------------------
CREATE TYPE STATE_TYPE AS ENUM ('OK', 'WARN', 'FAIL');
CREATE TABLE server (
	IDSERVER  SERIAL PRIMARY KEY,
	HOSTNAME		VARCHAR(128)	          NOT NULL,
	HOSTPORT		INT  DEFAULT 80           NOT NULL,
	URLPATH			VARCHAR(128) DEFAULT '/'  NOT NULL,
	RESPONSE_HOST   TEXT,
	LASTCHECK 		TIMESTAMP,
	CREATED		    TIMESTAMP   		      NOT NULL,
	ACTIVE	        BOOLEAN                   NOT NULL,
	STATE			STATE_TYPE				  NOT NULL,
	IPADRESS		VARCHAR(128)			  NOT NULL

);

CREATE TABLE users (
		IDUSER  SERIAL PRIMARY KEY,
		NAME           VARCHAR(128)      NOT NULL,
	    LOGIN          VARCHAR(16)       NOT NULL,
	    PASSWORD       VARCHAR(64)		 NOT NULL,
	    EMAIL		   VARCHAR(64)       NOT NULL,
	    CREATED		   TIMESTAMP   		 NOT NULL,
	    LASTLOGIN	   TIMESTAMP,
	    ACTIVE	       BOOLEAN           NOT NULL,
	    ADMIN	       BOOLEAN           NOT NULL

);
CREATE TABLE userLists(
    IDUSER INTEGER REFERENCES users ON DELETE CASCADE,
    IDSERVER INTEGER REFERENCES server ON DELETE CASCADE,
    PRIMARY KEY (IDUSER, IDSERVER)
);

INSERT INTO users (NAME, LOGIN, PASSWORD, EMAIL, CREATED, LASTLOGIN, ACTIVE, ADMIN)
    VALUES ('Vasya', 'admin', 'admin', 'admin@mail.ru', '1994-11-29', '2014-03-20', true, true);

INSERT INTO server (HOSTNAME, RESPONSE_HOST, LAST_CHECK, CREATED, ACTIVE, STATE, IP_ADRESS )
    VALUES ('ya.ru', 'good', '2014-03-19', '2014-03-01', true, 'OK', '10.12.12.1');

 INSERT INTO employeeLists (ID_EMPLOYEE, ID_SERVER)
 	VALUES (2,2);

DELETE FROM server WHERE ID_SERVER = 1;